project:
  type: website
  output-dir: docs

website:
  title: "A blog by Pramesh Gautam"
  site-url: https://www.pmgautam.com
  description: "Machine Learning, Deep Learning, and AI blog by Pramesh Gautam."
  google-analytics: G-QF37WT63GC
  favicon: cover_stable_diffusion.jpeg
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: cover_stable_diffusion.jpeg
    logo-alt: A blog by Pramesh Gautam
    background: primary
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pmgautam
      - icon: twitter
        href: https://twitter.com/pmgautam_
      - icon: linkedin
        href: https://www.linkedin.com/in/gautampramesh
    left:
      - text: "Blogs"
        file: index.qmd
  open-graph:
    site-name: "Pramesh Gautam's Blog"
    locale: en_US
  twitter-card:
    creator: "@pmgautam_"
    site: "@pmgautam_"
    card-style: summary_large_image
  comments:
    utterances:
      repo: pmgautam/pmgautam.com
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
execute:
  freeze: true
    



